### PR TITLE
Group selection

### PR DESCRIPTION
**Pull request by NsTremblay**
Added Bonsai layout to group selection.
Not too sure if I integrated all the possible behaviour in the tree.
Radio buttons are programmed to appear if the attribute has a valid group

### CODE REVIEW

**Comment by mwhitesi** [comment]
There are some lib conflicts.  Initially the new bonsai menus did not load for me because there are two copies of the UserGroups class.  Akiff originally put UserGroups class in <script type="text/javascript" src="/superphy/App/Lib/js/superphy_user_groups.js"></script>.  I see you compiled the UserGroups class into the main superphy.js class.  The former is being loaded.

matt_whiteside [9:50 AM]
We use superphy.js to include any classes/code that is needed on most superphy pages.  Its a bit of judgement call.  If its only needed on a cpl pages we create a separate library and link it in the header for those pages.  This UserGroups class though might be a good candidate for inclusion in the main superphy.js lib.  I dont know though how many pages include the user groups menu.  If its just this one page, it should probably be in a separate library.

**Comment by mwhitesi** [comment]
Top-level menus Stx1 and Stx2 subtypes should probably not have a radio button. Just the submenus: 1a, 1d, etc

**Comment by mwhitesi** [comment]
Custom groups could also be a tree menu rather than a drop-down box.  Format would be:
> Custom groups
   o Individual group1
   o Individual group2
   > Custom collection
     o Custom collection1
     o Custome collection2
    ....

Custom groups without an assigned collection will be in the 'Individuals' collection and should not be under a submenu

**Comment by NsTremblay** [comment]
Yes, I didn't make a custom group yet so I don't really know how to format it. I think the main motivation for the tree was to go in depth with the serotypes. For the Stx1 and Stx2 subtypes I'll try to remove those from the db. The group selection is also on the VF and NMR page.

**Comment by mwhitesi** [comment]
When you load a custom group, in the active group panel : "undefined" is listed as the name.

Also need to resolve conflicts with new master

**Comment by mwhitesi** [comment]
A couple of issues still remain:

1) Active group genomes not highlighted in the tree
Loading a group (which sets active group and selection) does not change the node icons in the tree.  Other methods of selecting do change the tree, for e.g. selecting genomes in table will alter the node icons.

2) Loading a custom user group, the active group name in the centre panel is still listed as 'undefined' (e.g. Active Group: undefined (2 genomes)). The genome number is correct though.

3) When creating a new group from the centre selection panel, the newly created group is not loaded as the active group (need to select and load from the side menu after creating).  It would be more streamlined if newly created groups were automatically loaded as the 'Active group'.

4) After creating a group, the Group name, Collection name and Description fields are not cleared.  A successful creation of a group, should display a message to the user e.g. "Success! group created", and the group creation fields should be cleared so users do not have to delete them to create additional groups.

**Comment by NsTremblay** [comment]
Not sure if I was able to solve point number 1

**Comment by mwhitesi** [comment]
Issues 1, 2 & 3 look to be resolved (see comment above)

For issue 4, success message is displayed, but the group field text boxes are not cleared after a group is created (forcing the user to do it).  Also the new group name drop down box in the selection panel is not syncing correctly.  New groups are not being added, and failed groups get added.  Can I make a suggestion, rather than work on fixing this new drop down box for the group name, i would hide the group name, collection, and description fields, showing only the buttons in the panel.  When a user clicks "Create group from selection" or "Update group with selection", a pop-up or form appears with the group name, collection and description fields. Once the group is created, the form disappears.  I think the text boxes are distracting from the true operations available, and since they are only needed in certain contexts they can be hidden until needed.

**Comment by NsTremblay** [comment]
Can we remove group creation in summary panel all together. It feels redundant

**Pull request closed without merging**
