### PR TITLE
Shiny fix

### PR DESCRIPTION
**Pull request by chadlaing**
Fixes issue #15, as well as removing deprecated files and fixing a few Perl errors.

### CODE REVIEW

**Comment by mwhitesi** [comment]
- Can't test on my computer, looks like test needs to be done on Giant... but maybe thats obvious.
- Need up-to-date matrices files to fully test shiny.  Those are still coming :)

**Comment by chadlaing** [comment]
Yes, this relies on the Giant server for the Shiny part; however, that is coded into the template. Your local installation should still work, even though the data is fetched from Giant.

**Comment by mwhitesi** [comment]
Ok yes, there only appears to be one issue stopping the shiny analysis and i think its related to the old matrices. So the page loads ok, but when running a group comparison I get the following JS error in the console:

Listening on http://127.0.0.1:52276
Error in m_binary[group_1_strains, ] : subscript out of bounds
Warning in if (is.na(x)) return(FALSE) :
  the condition has length > 1 and only the first element will be used
Warning in if (is.na(x)) return(FALSE) :
  the condition has length > 1 and only the first element will be used
Warning in if (is.na(x)) return(FALSE) :
  the condition has length > 1 and only the first element will be used
Error in m_binary[group_1_strains, ] : subscript out of bounds
Error in m_binary[group_1_strains, ] : subscript out of bounds

this suggests to me that SNP and pangenome matrix data is out-of-sync with the meta-data & genome list

**Comment by chadlaing** [comment]
Ok -- we can wait for the new data.

**Comment by chadlaing** [comment]
Deprecated by the recent re-working of Shiny.

**Pull request closed without merging**
