### PR TITLE
New virulence ontology for VF/AMR page. Need to check that categories…

### PR DESCRIPTION
**Pull request by amanji**
…/subcategories are approprate and merge where necessary.

### CODE REVIEW

**Comment by chadlaing** [comment]
I checkout out this branch, and the categories do not appear on the VF / AMR page, the area is blank where the category boxes should be.

**Comment by amanji** [comment]
I have to update the db for them to show up. I can check out this branch on Cybera for testing.

**Comment by chadlaing** [comment]
Can I run an update script here? Or do we need a new DB dump?

**Comment by amanji** [comment]
No you should just be able to run the update scripts/instructions and it will clean out the old terms, repopulate the new ones and map the terms accordingly.

**Comment by chadlaing** [comment]
Checked it out, everything works.
Still need to address Issue #25, but the results are returned correctly.
Will add a new issue for the ordering of the ontology categories.

**Pull request merged**
